export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  rating: number;
  category: string;
  isNew?: boolean;
  isFeatured?: boolean;
  description?: string;
  stock?: number;
  sku?: string;
}
export type MainProduct = {
  id: string; // UUID
  sub_category_id: string | null;
  handle: string;
  title: string;
  description?: string;
  featured_image?: string;
};

export type Category = {
  id?: string;
  title: string;
  seo_title: string;
  description: string;
  seo_description: string;
  handle: string;
  ispublished: boolean;
  sub_categories?: SubCategory[];
};
export interface SubCategory {
  id?: string; // UUID generated by the database
  title: string;
  seo_title: string;
  description: string;
  seo_description: string;
  handle: string;
  color: string;
  ispublished: boolean;
  category_id: string;
  featureImage: string;
}
export interface SubCategory {
  id?: string; // UUID generated by the database
  title: string;
  seo_title: string;
  description: string;
  seo_description: string;
  handle: string;
  count?: number;
  color: string;
  ispublished: boolean;
  category_id: string;
  featureImage: string;
}
export interface MenuT {
  title: string;
  handle: string;
  icon?: string;
  ispublished: boolean;
}
export interface WishlistItem {
  id: number;
  productId: number;
  product: Product;
}

export interface InventoryItem extends Product {
  sku: string;
  stock: number;
  status: "In Stock" | "Low Stock" | "Out of Stock";
  lastUpdated: string;
}
export type ResponseType = { success: boolean; message?: string };
